---
title: "Adults_Analysis"
author: "Lauren Oey"
date: "7/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

df1 <- read_csv("raw1.csv")
glimpse(df1)
df2 <- read_csv("raw2.csv")
glimpse(df2)
```

```{r}
df1 <- df1 %>%
  mutate(liarPlayer = ifelse(trialNumber %% 2 == 0, "blue", "red"),
         drawnBlue = 6 - drawnRed,
         trueDrawn = ifelse(liarPlayer == "red", drawnRed, drawnBlue)) %>%
  select(-c("roleCurrent"))

df2 <- df2 %>%
  mutate(trueDrawn = ifelse(liarPlayer == "red", drawnRed, drawnBlue))

final.df <- bind_rows(df1, df2) %>%
  filter(exptPart == "trial")

final.df %>%
  select(subjID, liarPlayer, trueDrawn, reportedDrawn, callBS) %>%
  arrange(trueDrawn, reportedDrawn, callBS)
```

```{r}
final.df %>%
  group_by(subjID, liarPlayer, trueDrawn) %>%
  summarise(reported=mean(reportedDrawn),
            se = sd(reportedDrawn)/sqrt(n())) %>%
  ggplot(aes(x=trueDrawn, y=reported)) +
  geom_line() +
  geom_abline(intercept = 0, slope = 1, colour="darkgray", linetype=2) +
  scale_x_continuous(limits=c(0,6)) +
  scale_y_continuous(limits=c(0,6)) +
  facet_grid(liarPlayer~subjID) +
  theme_bw()
```

```{r}
final.df %>%
  group_by(subjID, liarPlayer, reportedDrawn) %>%
  summarise(prop = sum(callBS==TRUE)/n()) %>%
  ggplot(aes(x=reportedDrawn, y=prop)) +
  geom_line() +
  scale_x_continuous(limits=c(0,6)) +
  scale_y_continuous(limits=c(0,1)) +
  facet_grid(liarPlayer~subjID) +
  theme_bw()
```

# Aggregated Data

```{r}
final.df %>%
  group_by(trueDrawn) %>%
  summarise(reported=mean(reportedDrawn),
            n = n(),
            se = sd(reportedDrawn)/sqrt(n)) %>%
  filter(n > 1) %>%
  ggplot(aes(x=trueDrawn, y=reported)) +
  geom_abline(intercept = 0, slope = 1, colour="darkgray", linetype=2, size=1) +
  geom_line(size=2, colour="purple3") +
  geom_ribbon(aes(ymin=reported-se, ymax=reported+se), alpha=0.3, fill="purple3") +
  ggtitle("Lying") +
  scale_x_continuous("True Marbles Drawn", limits=c(0,6), expand=c(0,0)) +
  scale_y_continuous("Reported Marbles Drawn", limits=c(0,6), expand=c(0,0)) +
  theme_bw()
ggsave("img/lying.png")
```

```{r}
final.df %>%
  group_by(reportedDrawn) %>%
  summarise(n = n(),
            prop = (sum(callBS==TRUE)+1)/(n+2),
            se = sqrt((prop*(1-prop)/n))) %>%
  filter(n > 1) %>%
  ggplot(aes(x=reportedDrawn, y=prop)) +
  geom_line(size=2, colour="purple3") +
  geom_ribbon(aes(ymin=prop-se, ymax=prop+se), alpha=0.3, fill="purple3") +
  ggtitle("Detecting") +
  scale_x_continuous("Reported Marbles Drawn", limits=c(0,6), expand=c(0,0)) +
  scale_y_continuous("Proportion Call BS", limits=c(-0.05,1.1), expand=c(0,0)) +
  theme_bw()
ggsave("img/detecting.png")
```