---
title: "visualizations"
author: "Lauren Oey"
date: "2/19/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
df <- read_csv("data.csv")
dem <- read_csv("demographic.csv") %>%
  select(subjID, startTime, DOB, gender)
```

```{r functions, include=FALSE}
reformatDate <- function(date){
  date.a <- as.Date(date, format="%m/%d/%Y")
  date.b <- as.Date(date, format="%m.%d.%Y")
  case_when(
    !is.na(date.a) ~ date.a,
    !is.na(date.b) ~ date.b,
    TRUE ~ as.Date(date, format="%Y-%m-%d")
  )
}
```

# reformat data

```{r}
df_unified <- df %>%
  mutate(k = ifelse(liarPlayer=="blue", drawnBlue, drawnRed), # account for which color the player chose to play as
         kstar = ifelse(liarPlayer=="blue", reportedBlue, reportedRed)) %>%
  select(subjID, playerColor, trialNumber, playerRole, k, kstar, callBS, redTrialScore, blueTrialScore, responseTime, trialTime, catchQuestion, catchKey, catchResponse) %>%
  left_join(dem, by="subjID") %>% # include demographic data
  mutate(DOT = as.Date(as.POSIXct(startTime/1000, origin="1970-01-01")), # make date of testing (DOT) readable for normal humans lol
         DOB = reformatDate(DOB), # use customized function to reformat date of birth (inputted by parent)
         age = as.numeric(DOT - DOB), # calculate participant age at time of testing
         age.months = age / (365.25/12), # participant age in months (double)
         age.years = age / 365.25) %>% # participant age in years (double)
  select(-age)
  

# get catch trial data for each participant
# 4 catch trials for each participant
# participants asked to "click on all the {red/blue} marbles."
df_catch <- df_unified %>%
  filter(catchQuestion != -1) %>% # filter only the catch trials
  select(subjID, playerColor, trialNumber, playerRole, responseTime, catchQuestion, catchKey, catchResponse) %>%
  mutate(catchKey = str_remove_all(catchKey, "\\[|\\]|\\'"), # parse the catch key and response arrays: remove outer bracket
         catchResponse = str_remove_all(catchResponse, "\\[|\\]|\\'")) %>%
  separate(catchKey, paste0("key_",0:6), sep=", ") %>% # separate comma-separated string into separate columns
  gather("choice.num", "value", starts_with("key_")) %>% # create one column with responses in long format
  separate(catchResponse, paste0("response_", 0:6), sep=", ") %>%
  gather("response.num", "response", starts_with("response_")) %>%
  mutate(response = as.logical(response),
         choice.num = str_extract(choice.num, "[^_]$")) %>% # pull out only #
  filter(choice.num == str_extract(response.num, "[^_]$")) %>% # filter so that only get matched question and response number for each row
  select(-response.num) %>%
  mutate(correct = (catchQuestion == value) == response) %>% # check if correct
  group_by(subjID) %>%
  summarise(percCatchCorr = sum(correct)/n()) # get percent correct for each participant

  
df_unified <- df_unified %>%
  filter(catchQuestion == -1) %>%
  left_join(select(df_catch, subjID, percCatchCorr), by="subjID") %>%
  select(-catchQuestion, -catchKey, -catchResponse) %>%
  filter(percCatchCorr == 1) # remove participants who don't get 100% correct on catch trials ... maybe this is too harsh but most participants succeed

# overall rate of lying
df_unified %>%
  filter(playerRole == "liar") %>%
  summarise(lyingRate = sum(k != kstar)/n())

# arrange participants by date of testing
df_unified %>%
  distinct(subjID, DOT) %>%
  arrange(DOT)

# ****** @Diana commenting this out so you can look at the full data*******
# df_unified <- df_unified %>%
#  filter(DOT >= "2021-09-01") # filter for expt version when instructions changed

# rate of lying for new expt kids
# df_unified %>%
#   filter(playerRole == "liar") %>%
#   summarise(lyingRate = sum(k != kstar)/n())
```







# Plots

## Catch Trials
```{r}
df_catch %>%
  arrange(percCatchCorr)

df_unified %>%
  distinct(subjID, percCatchCorr) %>%
  arrange(percCatchCorr)
```


## Sender 
```{r}
df_unified %>%
  filter(playerRole == "liar") %>%
  ggplot(aes(x=k, y=kstar)) +
  geom_jitter(colour="gray80", size=0.7) +
  stat_summary() +
  geom_abline(slope=1, linetype=2) +
  theme_bw()

df_unified %>%
  filter(playerRole == "liar") %>%
  mutate(age.years = floor(age.years)) %>%
  ggplot(aes(x=k, y=kstar)) +
  geom_jitter(aes(colour=subjID), size=0.7) +
  stat_summary() +
  geom_abline(slope=1, linetype=2) +
  guides(colour=FALSE) +
  facet_wrap(~age.years) +
  theme_bw()

df_unified %>%
  filter(playerRole == "liar") %>%
  mutate(age.years = floor(age.years)) %>%
  group_by(age.years) %>%
  summarise(lieRate = sum(k != kstar)/n())

df_unified %>%
  filter(playerRole == "liar", k != kstar) %>%
  mutate(age.years = floor(age.years),
         ksay3 = case_when(
           kstar > 3 ~ "above3",
           kstar < 3 ~ "below3",
           kstar == 3 ~ "equal3"
         )) %>%
  count(ksay3)

df_unified %>%
  filter(playerRole == "liar", k != kstar) %>%
  mutate(age.years = floor(age.years),
         k3 = case_when(
           k > 3 ~ "above3",
           k < 3 ~ "below3",
           k == 3 ~ "equal3"
         )) %>%
  count(k3)

df_unified %>%
  filter(playerRole == "liar") %>%
  mutate(subjID = paste(str_pad(floor(age.months), 3, pad="0"), "months --", subjID)) %>%
  count(subjID, k, kstar) %>%
  complete(subjID, k, kstar, fill=list(n=0)) %>%
  group_by(subjID, k) %>%
  mutate(prop = n/sum(n)) %>%
  ggplot(aes(x=k, y=kstar, fill=prop)) +
  geom_tile() +
  scale_x_continuous("true drawn", expand = c(0,0), breaks=0:6) +
  scale_y_continuous("reported", expand = c(0,0), breaks=0:6) +
  facet_wrap(~subjID)
```



```{r}
df_unified %>%
  filter(playerRole == "liar" & k != kstar) %>%
  ggplot(aes(x=k, y=kstar)) +
  geom_jitter() +
  stat_summary() +
  geom_smooth(method="lm") +
  geom_abline(slope=1, linetype=2) +
  ggtitle("lies") +
  theme_minimal()
```

NOTE: mean lie above vs below identity line, maybe more for kids


```{r}
df_unified %>%
  filter(playerRole == "liar") %>%
  mutate(truth = as.numeric(k == kstar)) %>%
  ggplot(aes(x=k, y=truth)) +
  stat_summary() +
  geom_smooth() +
  ggtitle("rate of telling the truth") +
  scale_y_continuous(limits=c(0,1)) +
  theme_minimal()
```


```{r}
df_unified %>%
  filter(playerRole == "liar") %>%
  count(k, kstar) %>%
  complete(k, kstar, fill=list(n=0)) %>%
  group_by(k) %>%
  mutate(prop = n/sum(n)) %>%
  ggplot(aes(x=k, y=kstar, fill=prop)) +
  geom_tile() +
  scale_x_continuous("true drawn", expand = c(0,0), breaks=0:6) +
  scale_y_continuous("reported", expand = c(0,0), breaks=0:6) +
  scale_fill_gradient2(low="white", mid="darkorchid", high="blue", midpoint=0.5, limits=c(0,1))

df_unified %>%
  filter(playerRole == "liar") %>%
  mutate(age.years = floor(age.years)) %>%
  count(age.years, k, kstar) %>%
  complete(age.years, k, kstar, fill=list(n=0)) %>%
  group_by(age.years, k) %>%
  mutate(prop = n/sum(n)) %>%
  ggplot(aes(x=k, y=kstar, fill=prop)) +
  geom_tile() +
  scale_x_continuous("true drawn", expand = c(0,0), breaks=0:6) +
  scale_y_continuous("reported", expand = c(0,0), breaks=0:6) +
  scale_fill_gradient2(low="white", mid="darkorchid", high="blue", midpoint=0.5, limits=c(0,1)) +
  facet_wrap(~age.years)

```


```{r}
df_unified %>%
  filter(playerRole == "detector") %>%
  mutate(callBS = as.numeric(callBS)) %>%
  ggplot(aes(x=kstar, y=callBS)) +
  geom_hline(yintercept=0.5, colour="gray40", lty=2) +
  stat_summary() +
  #stat_summary(geom="line") +
  geom_smooth() +
  scale_x_continuous("reported", breaks=0:6) +
  scale_y_continuous('responded "trick"') +
  theme_minimal()

df_unified %>%
  filter(playerRole == "detector") %>%
  mutate(age.years = floor(age.years),
         callBS = as.numeric(callBS)) %>%
  ggplot(aes(x=kstar, y=callBS, colour=subjID)) +
  geom_hline(yintercept=0.5, colour="gray40", lty=2) +
  geom_jitter() +
  stat_summary() +
  #stat_summary(geom="line") +
  geom_smooth(method="glm", se=FALSE, method.args = list(family = "binomial")) +
  scale_x_continuous("reported", breaks=0:6) +
  scale_y_continuous('responded "trick"') +
  facet_wrap(~age.years) +
  theme_minimal()

```



